//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        public int ExamId { get; set; }
        public Nullable<int> ExamType { get; set; }
        public string Name { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> MultiChoiceLimitCount { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Ststus { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> SubjectFlag { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<int> PassMarks { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> MarksType { get; set; }
        public string CourseName { get; set; }
        public string BatchName { get; set; }
        public string TransactionDateStr { get; set; }
        public Nullable<int> StudentExamDetailsId { get; set; }
    }
}
