//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamQuestionPaperCO
    {
        public int ExamQuestionId { get; set; }
        public Nullable<int> ExamId { get; set; }
        public string QuestionName { get; set; }
        public Nullable<int> QuestionType { get; set; }
        public string Answer { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> QuestionNo { get; set; }

        public List<string> OptionValue { get; set; }

        public string StatusFlagDesc { get; set; }

        public int? Ststus { get; set; }
    }
}
