//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeParticular
    {
        public int FeeParticularID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Tax { get; set; }
        public string Discount { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> FeeID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public SchoolCO SchoolCO { get; internal set; }
    }
}
