//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeSubscription
    {
        public int FeeSubscriptionID { get; set; }
        public Nullable<int> FeeID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> NumberOfSubscription { get; set; }
        public Nullable<int> SubscriptionType { get; set; }
        public Nullable<int> RecurringInterval { get; set; }
        public Nullable<int> DayOfMonth { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public Nullable<System.DateTime> DueDate1 { get; set; }
        public Nullable<System.DateTime> DueDate2 { get; set; }
        public Nullable<System.DateTime> DueDate3 { get; set; }
        public Nullable<System.DateTime> DueDate4 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DueDate5 { get; set; }
    }
}
