//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratePaySlip
    {
        public int Id { get; set; }
        public Nullable<int> EmpNo { get; set; }
        public Nullable<System.DateTime> SalaryDate { get; set; }
        public string BasicPay { get; set; }
        public string Incentive { get; set; }
        public string OverTime { get; set; }
        public string Hike { get; set; }
        public string EarnTotal { get; set; }
        public string TDS { get; set; }
        public string LossofPay { get; set; }
        public string Loan { get; set; }
        public string FestivalBonus { get; set; }
        public string ESI { get; set; }
        public string EPF { get; set; }
        public string Total_Deduction { get; set; }
        public string Net_Salary { get; set; }
        public string Note { get; set; }
    }
}
