//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GS247Entities8 : DbContext
    {
        public GS247Entities8()
            : base("name=GS247Entities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityFeed> ActivityFeeds { get; set; }
        public virtual DbSet<batch> batches { get; set; }
        public virtual DbSet<BatchLink> BatchLinks { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CBSEExamSetting> CBSEExamSettings { get; set; }
        public virtual DbSet<ComplaintCategory> ComplaintCategories { get; set; }
        public virtual DbSet<ComplaintRegister> ComplaintRegisters { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<CoursesSubjectsLink> CoursesSubjectsLinks { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<DocumentUpload> DocumentUploads { get; set; }
        public virtual DbSet<ExamCommonTypeBatchSubject> ExamCommonTypeBatchSubjects { get; set; }
        public virtual DbSet<ExamCommonTypeCourse> ExamCommonTypeCourses { get; set; }
        public virtual DbSet<ExamFormat> ExamFormats { get; set; }
        public virtual DbSet<ExamGradeLevel> ExamGradeLevels { get; set; }
        public virtual DbSet<Examination> Examinations { get; set; }
        public virtual DbSet<ExamQuestionPaper> ExamQuestionPapers { get; set; }
        public virtual DbSet<ExamQuestionTypeValue> ExamQuestionTypeValues { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<FeeAccess> FeeAccesses { get; set; }
        public virtual DbSet<FeeParticular> FeeParticulars { get; set; }
        public virtual DbSet<FeesConfiguration> FeesConfigurations { get; set; }
        public virtual DbSet<FeeSubRecurringCustomDetail> FeeSubRecurringCustomDetails { get; set; }
        public virtual DbSet<FeeSubscription> FeeSubscriptions { get; set; }
        public virtual DbSet<FileUpload> FileUploads { get; set; }
        public virtual DbSet<GatewaySetting> GatewaySettings { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<GenerateSequenceMaster> GenerateSequenceMasters { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GuardianDetail> GuardianDetails { get; set; }
        public virtual DbSet<HostelDetail> HostelDetails { get; set; }
        public virtual DbSet<HostelFloorDetail> HostelFloorDetails { get; set; }
        public virtual DbSet<HostelMessDetail> HostelMessDetails { get; set; }
        public virtual DbSet<HostelRoomBedDetail> HostelRoomBedDetails { get; set; }
        public virtual DbSet<HostelRoomDetail> HostelRoomDetails { get; set; }
        public virtual DbSet<LibraryAuthor> LibraryAuthors { get; set; }
        public virtual DbSet<LibraryBook> LibraryBooks { get; set; }
        public virtual DbSet<LibraryBooksIssue> LibraryBooksIssues { get; set; }
        public virtual DbSet<LibraryCategory> LibraryCategories { get; set; }
        public virtual DbSet<MatchField> MatchFields { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<PurchaseApplyOrder> PurchaseApplyOrders { get; set; }
        public virtual DbSet<PurchaseItem> PurchaseItems { get; set; }
        public virtual DbSet<PurchaseItemsStockDetail> PurchaseItemsStockDetails { get; set; }
        public virtual DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual DbSet<PurchaseProductDetail> PurchaseProductDetails { get; set; }
        public virtual DbSet<PurchaseSaleDetail> PurchaseSaleDetails { get; set; }
        public virtual DbSet<PurchaseVendorDetail> PurchaseVendorDetails { get; set; }
        public virtual DbSet<RequestMaterialDetail> RequestMaterialDetails { get; set; }
        public virtual DbSet<semester> semesters { get; set; }
        public virtual DbSet<SettingsModel> SettingsModels { get; set; }
        public virtual DbSet<SettingsOnlineRegistration> SettingsOnlineRegistrations { get; set; }
        public virtual DbSet<SettingsUserRole> SettingsUserRoles { get; set; }
        public virtual DbSet<StaffContactDetail> StaffContactDetails { get; set; }
        public virtual DbSet<StaffLeaveRequest> StaffLeaveRequests { get; set; }
        public virtual DbSet<StaffLeaveType> StaffLeaveTypes { get; set; }
        public virtual DbSet<StaffLogCategory> StaffLogCategories { get; set; }
        public virtual DbSet<StaffSalaryDetail> StaffSalaryDetails { get; set; }
        public virtual DbSet<StudentAchievement> StudentAchievements { get; set; }
        public virtual DbSet<StudentCategory> StudentCategories { get; set; }
        public virtual DbSet<StudentDetail> StudentDetails { get; set; }
        public virtual DbSet<StudentDocument> StudentDocuments { get; set; }
        public virtual DbSet<StudentExamAnswerDetail> StudentExamAnswerDetails { get; set; }
        public virtual DbSet<StudentExamDetail> StudentExamDetails { get; set; }
        public virtual DbSet<StudentFeesInvoice> StudentFeesInvoices { get; set; }
        public virtual DbSet<StudentFieldSetting> StudentFieldSettings { get; set; }
        public virtual DbSet<StudentHostelFeesMailNotification> StudentHostelFeesMailNotifications { get; set; }
        public virtual DbSet<StudentHostelFeesPaidDetail> StudentHostelFeesPaidDetails { get; set; }
        public virtual DbSet<StudentHostelRoomChangelNotification> StudentHostelRoomChangelNotifications { get; set; }
        public virtual DbSet<StudentInstutionDetail> StudentInstutionDetails { get; set; }
        public virtual DbSet<StudentInvoicePayment> StudentInvoicePayments { get; set; }
        public virtual DbSet<StudentInvoiceTransaction> StudentInvoiceTransactions { get; set; }
        public virtual DbSet<StudentLeaveType> StudentLeaveTypes { get; set; }
        public virtual DbSet<StudentLog> StudentLogs { get; set; }
        public virtual DbSet<StudentLogCategory> StudentLogCategories { get; set; }
        public virtual DbSet<StudentRoomDetail> StudentRoomDetails { get; set; }
        public virtual DbSet<StudentSearchFilter> StudentSearchFilters { get; set; }
        public virtual DbSet<StudentWaitingList> StudentWaitingLists { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<TeachersManageCategory> TeachersManageCategories { get; set; }
        public virtual DbSet<TeachersManageDepartment> TeachersManageDepartments { get; set; }
        public virtual DbSet<TeachersManageGrade> TeachersManageGrades { get; set; }
        public virtual DbSet<TeachersManagePosition> TeachersManagePositions { get; set; }
        public virtual DbSet<Timetable> Timetables { get; set; }
        public virtual DbSet<Timetable_ClassTimings> Timetable_ClassTimings { get; set; }
        public virtual DbSet<Timetable_Weekdays> Timetable_Weekdays { get; set; }
        public virtual DbSet<TransportAttendanceByRoute> TransportAttendanceByRoutes { get; set; }
        public virtual DbSet<TransportBusLog> TransportBusLogs { get; set; }
        public virtual DbSet<TransportDriver> TransportDrivers { get; set; }
        public virtual DbSet<TransportDriverVehicleLink> TransportDriverVehicleLinks { get; set; }
        public virtual DbSet<TransportRoute> TransportRoutes { get; set; }
        public virtual DbSet<TransportStop> TransportStops { get; set; }
        public virtual DbSet<TransportStudentAttendanceLog> TransportStudentAttendanceLogs { get; set; }
        public virtual DbSet<TransportStudentRouteLink> TransportStudentRouteLinks { get; set; }
        public virtual DbSet<TransportVehicle> TransportVehicles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Year> Years { get; set; }
        public virtual DbSet<BatchCourseLink> BatchCourseLinks { get; set; }
        public virtual DbSet<BatchSubjectsLink> BatchSubjectsLinks { get; set; }
        public virtual DbSet<EventsDetail> EventsDetails { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<GeneratePaySlip> GeneratePaySlips { get; set; }
        public virtual DbSet<MailBox> MailBoxes { get; set; }
        public virtual DbSet<NewsFeed> NewsFeeds { get; set; }
        public virtual DbSet<SettingsAttendance> SettingsAttendances { get; set; }
        public virtual DbSet<SettingsCommonClassTiming> SettingsCommonClassTimings { get; set; }
        public virtual DbSet<SettingsDashboard> SettingsDashboards { get; set; }
        public virtual DbSet<SettingsDefaultGrading> SettingsDefaultGradings { get; set; }
        public virtual DbSet<SettingsDefaultWeekday> SettingsDefaultWeekdays { get; set; }
        public virtual DbSet<SettingsDocumentType> SettingsDocumentTypes { get; set; }
        public virtual DbSet<SettingsExamFormat> SettingsExamFormats { get; set; }
        public virtual DbSet<SettingsFeature> SettingsFeatures { get; set; }
        public virtual DbSet<SettingsNotification> SettingsNotifications { get; set; }
        public virtual DbSet<SettingsSchoolSetup> SettingsSchoolSetups { get; set; }
        public virtual DbSet<SettingsSMSCounter> SettingsSMSCounters { get; set; }
        public virtual DbSet<SettingsSMSGateway> SettingsSMSGateways { get; set; }
        public virtual DbSet<SettingsSMSGatewayParameter> SettingsSMSGatewayParameters { get; set; }
        public virtual DbSet<SettingsSMTP> SettingsSMTPs { get; set; }
        public virtual DbSet<SettingsTimeTableFormat> SettingsTimeTableFormats { get; set; }
        public virtual DbSet<Staff_Attendance> Staff_Attendance { get; set; }
        public virtual DbSet<StaffDetail> StaffDetails { get; set; }
        public virtual DbSet<StudentAttendance> StudentAttendances { get; set; }
        public virtual DbSet<tbl_timetable_defaultweekday> tbl_timetable_defaultweekday { get; set; }
        public virtual DbSet<TeacherAchievement> TeacherAchievements { get; set; }
        public virtual DbSet<TeacherDocument> TeacherDocuments { get; set; }
        public virtual DbSet<TeacherLog> TeacherLogs { get; set; }
        public virtual DbSet<TeachersLogCategory> TeachersLogCategories { get; set; }
        public virtual DbSet<TeachersPositionCategoryLink> TeachersPositionCategoryLinks { get; set; }
        public virtual DbSet<TeacherSubjectAssociation> TeacherSubjectAssociations { get; set; }
        public virtual DbSet<VW_MailStatusMaster> VW_MailStatusMaster { get; set; }
    }
}
