//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryBook
    {
        public int Id { get; set; }
        public string ISBN { get; set; }
        public string Title { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string Edition { get; set; }
        public string Publisher { get; set; }
        public string Copy { get; set; }
        public string BookPosition { get; set; }
        public string ShelfNo { get; set; }
        public string CopiesAvailable { get; set; }
    }
}
