//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryBooksIssue
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> BookId { get; set; }
        public string IssueDate { get; set; }
        public string DueDate { get; set; }
        public Nullable<int> isReturned { get; set; }
        public string ReturnDate { get; set; }
    }
}
