//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailBox
    {
        public int Id { get; set; }
        public string FromMailId { get; set; }
        public string ToMailIds { get; set; }
        public string CCMailIds { get; set; }
        public string BCCMailIds { get; set; }
        public string MailBody { get; set; }
        public string Attachments { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string Subject { get; set; }
        public string ToGroup { get; set; }
        public string Read { get; set; }
        public string Delete { get; set; }
        public string SenderGroup { get; set; }
    }
}
