//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseSaleDetail
    {
        public int SaleDetailsId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> PurchaserType { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> PurchasedBy { get; set; }
        public Nullable<int> StatsuFlag { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string ReturnReason { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
