//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsNotification
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IsSMS { get; set; }
        public Nullable<int> IsEmail { get; set; }
        public Nullable<int> IsMessage { get; set; }
        public Nullable<int> IsStudent { get; set; }
        public Nullable<int> IsGuardian { get; set; }
        public Nullable<int> IsTeacher { get; set; }
    }
}
