//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsSMSGateway
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public Nullable<int> Method { get; set; }
        public string ResponseFormat { get; set; }
    }
}
