//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsOnlineRegistration
    {
        public int Id { get; set; }
        public Nullable<int> AcademicYearId { get; set; }
        public Nullable<int> AllowOnlineAdmission { get; set; }
        public Nullable<int> ShowLink { get; set; }
    }
}
