//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsSchoolSetup
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string RegistrationId { get; set; }
        public string FoundedOn { get; set; }
        public string Curriculum { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string Phone { get; set; }
        public string AlternatePhone { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string PrincipalName { get; set; }
        public string PrincipalEmail { get; set; }
        public string PrincipalPhone { get; set; }
        public string PrincipalMobile { get; set; }
        public Nullable<int> CurrentAcademicYear { get; set; }
        public string FinanceYearStart { get; set; }
        public string FinanceYearEnd { get; set; }
    }
}
