//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Attendance
    {
        public int Id { get; set; }
        public Nullable<int> Staff_Number { get; set; }
        public string Staff_Name { get; set; }
        public Nullable<System.DateTime> Attendance_Date { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
