//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDetail
    {
        public int TeacherId { get; set; }
        public string TeacherNumber { get; set; }
        public string JoiningDate { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string DateOfBirth { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string JobTitle { get; set; }
        public string Qualification { get; set; }
        public string TotalExpYears { get; set; }
        public string TotalExpMonths { get; set; }
        public string ExperienceDetails { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> ChildrenCount { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SpouseName { get; set; }
        public Nullable<int> BloodGroup { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string Email { get; set; }
        public string PhotoPath { get; set; }
        public string HomeAddressLine1 { get; set; }
        public string HomeAddressLine2 { get; set; }
        public string HomeCity { get; set; }
        public string HomeState { get; set; }
        public string HomeCountry { get; set; }
        public string HomePinCode { get; set; }
        public string OfficeAddressLine1 { get; set; }
        public string OfficeAddressLine2 { get; set; }
        public string OfficeCity { get; set; }
        public string OfficeState { get; set; }
        public string OfficeCountry { get; set; }
        public string OfficePinCode { get; set; }
        public string OficePhone1 { get; set; }
        public string OfficePhone2 { get; set; }
        public string MobileNumber { get; set; }
        public string HomePhone { get; set; }
        public string Fax { get; set; }
        public Nullable<int> StaffRoleId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    }
}
