//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffSalaryDetail
    {
        public int StaffSalaryId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public string BasicPay { get; set; }
        public string EPF { get; set; }
        public string ESI { get; set; }
        public string TDSValue { get; set; }
        public string BankName { get; set; }
        public string BankAccountNo { get; set; }
        public string IFSCCode { get; set; }
        public string PassportNo { get; set; }
        public string PassportExpiryDate { get; set; }
        public string PANCardNo { get; set; }
        public string AadhaarNo { get; set; }
    }
}
