//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInvoiceTransaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public string TransactionNumber { get; set; }
        public string Description { get; set; }
        public string InvoicePaymentAmount { get; set; }
        public Nullable<int> StatusFlag { get; set; }
        public string proof { get; set; }
        public string FileName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
