//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFieldSetting
    {
        public int StudentFieldSettingID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Required { get; set; }
        public Nullable<int> FieldTypeFlag { get; set; }
        public Nullable<int> CheckAllFlag { get; set; }
        public Nullable<int> AdminStudentRegistrationFormFlag { get; set; }
        public Nullable<int> OnlineAdmissionFormFlag { get; set; }
        public Nullable<int> ParentPortalFlag { get; set; }
        public Nullable<int> StudentProfileFlag { get; set; }
        public Nullable<int> StudentProfilePDFFlag { get; set; }
        public Nullable<int> StudentPortalFlag { get; set; }
        public Nullable<int> TeacherPortalFlag { get; set; }
        public Nullable<int> TabSelection { get; set; }
        public Nullable<int> TabSubSelection { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Category { get; set; }
        public Nullable<int> StatusFlag { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string ColumnMapping { get; set; }
    }
}
