//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSearchFilter
    {
        public int SearchFilterdId { get; set; }
        public string Category { get; set; }
        public string SearchFilterdName { get; set; }
        public string FileldName { get; set; }
        public string SearchValue { get; set; }
        public string OptionValue { get; set; }
        public Nullable<int> userId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
