//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentExamDetail
    {
        public int StudentExamDetailsId { get; set; }
        public Nullable<int> ExamId { get; set; }
        public Nullable<int> StudentDetailsId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string LoginId { get; set; }
        public string TotalMark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Grade { get; set; }
        public Nullable<int> StatusFlag { get; set; }
        public Nullable<int> MarkType { get; set; }
        public string StudentName { get; set; }
        public string AdmissionNo { get; set; }
    }
}
