//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentDetail()
        {
            this.TransportStudentAttendanceLogs = new HashSet<TransportStudentAttendanceLog>();
        }
    
        public int StudentDetailsId { get; set; }
        public string AdmissionNo { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string StudentId { get; set; }
        public Nullable<int> Batch { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Blood { get; set; }
        public string BirthPlace { get; set; }
        public string Language { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string Religion { get; set; }
        public Nullable<int> StudentCategory { get; set; }
        public Nullable<int> PromitionalFlag { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string Email { get; set; }
        public string FileName { get; set; }
        public string Data { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> DeleteFlag { get; set; }
        public string RollNumber { get; set; }
        public string Semester { get; set; }
        public string AcademicYear { get; set; }
        public Nullable<int> AcademicStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> OnlineStatus { get; set; }
        public Nullable<int> OnlineApplicationStatus { get; set; }
        public Nullable<int> Course { get; set; }
    
        public virtual TransportStudentRouteLink TransportStudentRouteLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportStudentAttendanceLog> TransportStudentAttendanceLogs { get; set; }
    }
}
