//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeesInvoice
    {
        public int InvoiceID { get; set; }
        public Nullable<int> StudentDetailsId { get; set; }
        public Nullable<int> FeeId { get; set; }
        public string InvoiceAmount { get; set; }
        public Nullable<int> PaidStatusFlag { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> FeeAccessID { get; set; }
        public Nullable<int> FeeParticularID { get; set; }
        public Nullable<int> CancelFlag { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> BatchId { get; set; }
        public string TotalAmount { get; set; }
        public string DiscountAmount { get; set; }
        public string TaxAmount { get; set; }
        public SchoolCO SchoolCO { get; internal set; }
    }
}
