//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_timetable_defaultweekday
    {
        public long refid { get; set; }
        public Nullable<int> is_sunday { get; set; }
        public Nullable<int> is_monday { get; set; }
        public Nullable<int> is_tuesday { get; set; }
        public Nullable<int> is_wednesday { get; set; }
        public Nullable<int> is_thursday { get; set; }
        public Nullable<int> is_friday { get; set; }
        public Nullable<int> is_saturday { get; set; }
    }
}
