//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherAchievement
    {
        public int Id { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public string AchievementTitle { get; set; }
        public string Description { get; set; }
        public string DocumentName { get; set; }
        public string DocumentPath { get; set; }
    }
}
