//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherLog
    {
        public int Id { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string LogDetails { get; set; }
        public Nullable<int> UserId { get; set; }
        public string LoggedDateTime { get; set; }
    }
}
