//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportRoute
    {
        public int RouteId { get; set; }
        public string RouteName { get; set; }
        public Nullable<int> NoOfStops { get; set; }
        public Nullable<int> NoOfStudents { get; set; }
        public string VehicleCode { get; set; }
    }
}
