//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportVehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportVehicle()
        {
            this.TransportBusLogs = new HashSet<TransportBusLog>();
        }
    
        public int Id { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleCode { get; set; }
        public Nullable<int> NoOfSeats { get; set; }
        public Nullable<int> MaximumCapacity { get; set; }
        public string VehicleType { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Phone { get; set; }
        public string Insurance { get; set; }
        public string TaxRemitted { get; set; }
        public string Permit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportBusLog> TransportBusLogs { get; set; }
    }
}
