//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GS247.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Year
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string StartsOn { get; set; }
        public string EndsOn { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
